application:
  name: trail
  project: NSUT-HUB
  cloud_region: aws/us-west-2
  publicly_accessible: true
databases:
- type: postgresql
  version: "11.5"
  name: my-postgresql-6132005
routers:
- name: main
  routes:
  - application_name: trail
    paths:
    - /*
